# Cloud Platforms {#platforms}

After sensors start to send data it is necessary that you define a place where that data should be stored. In the context of IoT the Cloud is a place somewhere on the internet where a provider allows recognized sensors to store their raw data in a database. You as the owner has access to that database, are able to program it and know how results could be made visible on dashboards. So it is not necessary anymore to maintain your own private servers in your own data centers, but cloud platform companies are now taking over that role.

Raw data is in fact meaningless. You will have to analyze it, reshuffle, run statistics on it, correlate it with other data, watch for exceptional values and so on to make raw sensor data valuable for your business goals. We will touch on data analytics, machine learning and Data Science in [section 13](#analytics).

We will look into cloud platforms, their place in the IoT infrastructure and explore one of the many cloud solutions.

## Data in the cloud
As most IoT devices have very limited memory resources, the data they produce has to be stored elsewhere. We discussed the data communication possibilities in [section 8](#communication). In theory the data could be gathered into a simple text file and applications could read from this source.

However we soon would encounter some annoying practical problems. For instance while data is written to a text file it is blocked. This would mean other devices can not add their data resulting in data loss. Also a text file is not the most efficient user of memory and its size would grow exponentially when used in a professional application with large numbers of devices and users. Other issues include lack of search and filtering facilities and connecting to other data tables.

The above mentioned problems are not uniquely related to the IoT system. It translates to any client server environment. Database systems have been developed to cope with the challenges of efficiently creating large quantities of data, read records, and update and delete them. These basic database functionalities have been summarized in the CRUD accronym. 



You as the owner has access to that database, are able to program it and know how results could be made visible on dashboards. So it is not necessary anymore to maintain your own private servers in your own data centers, but cloud platform companies are now taking over that role.

## Things in a network

## Amazon Web Services


