--- 
title: "Internet of Things for Smart Industry"
author: "Franz Maurer, Witek ten Hove & Deny Smeets"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a accompanying book to the HAN Minor Smart Industry"
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

# Welcome

This is an accompanying book to the HAN Minor Smart Industry and covers the major topics regarding the Internet of Things (IoT) implementation in an industrial setting.


<!--chapter:end:index.Rmd-->

#  - Introduction to IoT {#intro}

The IoT is the product of physical objects, controllers, sensors and actuators and the internet [@mcewen_designing_2013]. The first reference to the IoT was in 1982, when researchers at Carnegie Mellon University developed the world’s first IoT-enabled Coke Machine. Mark Weiser developed the concept further in the early 90s; and Kevin Ashton coined the term ‘Internet of Things’ around 1999.

<!--chapter:end:01-intro.Rmd-->

# IoT Capabilities {#capabilities}

<video width="400" height="300" controls>
  <source src="./docs/iotbook_files/vids/design.mp4">
  Your browser does not support this format.
</video>

<!--chapter:end:02-capabilities.Rmd-->

# IoT Framework {#framework}

We describe our methods in this chapter.

<!--chapter:end:03-framework.Rmd-->

# IoT Markets {#markets}

Some _significant_ applications are demonstrated in this chapter.

## Example one

## Example two

<!--chapter:end:04-markets.Rmd-->

# IoT Fundamentals {#fundamentals}

We have finished a nice book.

<!--chapter:end:05-fundamentals.Rmd-->

# Sensors {#sensors}

We have finished a nice book.

<!--chapter:end:06-sensors.Rmd-->

# Data Communication {#communications}

We have finished a nice book.

<!--chapter:end:07-communication.Rmd-->

# Cloud Platforms {#platforms}

We have finished a nice book.

<!--chapter:end:08-cloud.Rmd-->

# Privacy {#privacy}

We have finished a nice book.

<!--chapter:end:09-privacy.Rmd-->

# Security {#security}

We have finished a nice book.

<!--chapter:end:10-security.Rmd-->

# Encryption {#encryption}

We have finished a nice book.

<!--chapter:end:11-encryption.Rmd-->

# Data Analytics {#analytics}

We have finished a nice book.

<!--chapter:end:12-analytics.Rmd-->

# Dashboards and Apps {#apps}

We have finished a nice book.

<!--chapter:end:13-apps.Rmd-->

# Arduino Programming {#arduino}

We have finished a nice book.

<!--chapter:end:14-arduino.Rmd-->

`r if (knitr:::is_html_output()) '# References {-}'`

<!--chapter:end:15-references.Rmd-->

